services:
  sftp-server:
    container_name: "sftp_server"
    image: atmoz/sftp:latest
    ports:
      - "22:22"
    volumes:
      - ./sftp/data:/home/user/data
      - ./sftp/init.sh:/etc/sftp.d/init.sh:rw
    command:
      - user:pass:::data

  postgres:
    container_name: "postgres"
    image: postgres:latest
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
      - POSTGRES_RESTORE_STRATEGY=${POSTGRES_RESTORE_STRATEGY:-always}
    ports:
      - "5432:5432"